# Generated by Django 4.2.3 on 2023-07-07 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
